/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sat Dec 16 21:02:12 2017. */

#include "sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Data_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, Data, SensorID, SensorID, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, Data, ChannelID, SensorID, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Data, Status, ChannelID, 0),
    PB_FIELD(  4, INT32   , REPEATED, CALLBACK, OTHER, Data, Value, Status, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
